# Generated by Django 4.2 on 2023-04-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admindata',
            old_name='admailid',
            new_name='admail',
        ),
    ]
