# Generated by Django 4.2 on 2023-05-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=20)),
                ('empmail', models.EmailField(max_length=254)),
                ('empphone', models.BigIntegerField()),
                ('emppwd', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
