# Generated by Django 4.2.1 on 2023-06-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_productcategory_catimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employdata',
            name='designation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
