# Generated by Django 4.2.1 on 2023-06-05 06:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employdata_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=20)),
                ('taskdesc', models.CharField(max_length=20)),
                ('assigndate', models.DateField(default=django.utils.timezone.now)),
                ('duedate', models.DateField()),
                ('timeofcomp', models.TimeField()),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField(default=False)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employdata')),
            ],
        ),
    ]
