# Generated by Django 4.2 on 2023-04-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('umail', models.EmailField(max_length=254)),
                ('uphone', models.BigIntegerField()),
                ('uaddr', models.CharField(max_length=30)),
                ('ucity', models.CharField(max_length=20)),
                ('uzip', models.CharField(max_length=20)),
                ('ustate', models.CharField(max_length=20)),
                ('ucountry', models.CharField(max_length=20)),
                ('utype', models.CharField(max_length=20)),
                ('ucompany', models.CharField(max_length=20)),
                ('upwd', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
