# Generated by Django 4.2 on 2023-04-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='ucompany',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='utype',
        ),
    ]
