# Generated by Django 4.2 on 2023-04-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsuser', '0002_remove_customers_ucompany_remove_customers_utype'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='uimage',
            field=models.FileField(default='default_image.png', upload_to='users'),
        ),
    ]
