# Generated by Django 4.2 on 2023-05-22 08:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_productcategory_catimage'),
        ('imsuser', '0004_alter_customers_uimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uprodqty', models.BigIntegerField(default=1)),
                ('addingtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('uprodid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.product')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsuser.customers')),
            ],
        ),
    ]
