# Generated by Django 4.2 on 2023-05-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsuser', '0009_cart_status_alter_customers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
