# Generated by Django 4.2.1 on 2023-05-31 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imsuser', '0012_newaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='addingtime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='addingtime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
