# Generated by Django 4.2.1 on 2023-05-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsuser', '0013_order_alter_cart_addingtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cartid',
            field=models.ManyToManyField(to='imsuser.cart'),
        ),
    ]
