# Generated by Django 4.2.1 on 2023-05-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsuser', '0015_alter_wishlist_addingtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='addingtime',
            new_name='waddingdate',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='addingtime',
            new_name='addingdate',
        ),
    ]
