# Generated by Django 4.2.1 on 2023-05-31 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imsuser', '0016_rename_addingtime_cart_waddingdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='waddingdate',
            new_name='addingdate',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='addingdate',
            new_name='waddingdate',
        ),
    ]
