# Generated by Django 4.2.1 on 2023-06-01 06:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imsuser', '0017_rename_waddingdate_cart_addingdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderdate',
            field=models.DateField(default=datetime.date(2023, 6, 1)),
        ),
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsuser.customers'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='waddingdate',
            field=models.DateField(default=datetime.date(2023, 6, 1)),
        ),
    ]
