from django.shortcuts import *
from.models import*
from django.contrib import messages
from company.models import *
from supplier.models import*
from django.core.mail import send_mail
import string,random
from IMS.settings import EMAIL_HOST_USER
def adminlogin(request):
   if request.method=='POST':
      try:
         admail=request.POST['admail']
         adpwd=request.POST['adpwd']
         check=Admindata.objects.get(admail=admail,adpwd=adpwd)
         request.session['admail']=check.admail
         request.session['adpwd']=check.adpwd
         return redirect('adhome')
      except Admindata.DoesNotExist as e:
         messages.info(request,"Invalid Credentials")
   return render(request,'imsadmin/adminlogin.html')
def adminreg(request):
   if request.method=='POST':
      name=request.POST['adname']
      mail=request.POST['admail']
      pwd=request.POST['adpwd']
      saveval=Admindata(adname=name,admail=mail,adpwd=pwd)   
      saveval.save()
   return render(request,'imsadmin/adminreg.html')

def adhome(request):
   return render(request,'imsadmin/adhome.html')
#company functions  
def companies(request):
   comp=Companies.objects.all()
   context={
      'comp':comp
   }
   return render(request,'imsadmin/companies.html',context)
def capprove(request, id):
    company = Companies.objects.get(id=id)
    if company.reject:
        message = "This company cannot be approved because it has already been rejected"
        return render(request, 'imsadmin/error.html', {'message': message})
    else:
        Companies.objects.filter(id=id).update(approve=True)
        comp = Companies.objects.all()
        context = {
            'comp': comp
        }
        return render(request, 'imsadmin/companies.html', context)

def creject(request, id):
    company = Companies.objects.get(id=id)
    if company.approve:
        message = "This company cannot be rejected because it has already been approved."
        return render(request, 'imsadmin/error.html', {'message': message})
    else:
        Companies.objects.filter(id=id).update(reject=True)
        comp = Companies.objects.all()
        context = {
            'comp': comp
        }
        return render(request, 'imsadmin/companies.html', context)

def send_cmail(request,id):
   comp=Companies.objects.get(id=id)
   #sub = forms.Subscribe()
   if request.method == 'POST':
        sub = request.POST['email']
        name= request.POST['name']
        subject = 'Hi, '+format(name) 
        recepient = str(sub)
      
        # get random password pf length 8 with letters, digits, and symbols
        characters = string.ascii_letters + string.digits + string.punctuation
        password = ''.join(random.choice(characters) for i in range(8))
        Companies.objects.filter(id=id).update(cppwd=password)
        
        message = '''Welcome to OurWorkGem site.
        you can change automatically generated password after login to your profile
        Steps you should follow for changing password:
        1) Login your profile with autogenerated password
        2) After click on the profile button in the home page
        3) In that profile click on the change password button then you change the password
        You can login with this password : ''' +format(password)
        send_mail(subject, 
            message, EMAIL_HOST_USER, [recepient], fail_silently = False)
   return render(request,'imsadmin/send_cmail.html',{'comp':comp})
def send_crejmail(request,id):
   comp=Companies.objects.get(id=id)
   if request.method == 'POST':
        sub = request.POST['email']
        name= request.POST['name']
        subject = 'Hi, '+format(name) 
        recepient = str(sub)
      
        # get random password pf length 8 with letters, digits, and symbols
        #characters = string.ascii_letters + string.digits + string.punctuation
        #password = ''.join(random.choice(characters) for i in range(8))
        #Suppliers.objects.filter(id=id).update(sppwd=password)
        #Companies.objects.filter(id=id).update(cppwd=password)
        
        message = '''Thank you for your interest in becoming a registered Company for using the Online IMS.
          We appreciate your time and effort in completing the registration process.
          After careful consideration, we regret to inform you that we will not be able
          to proceed with your system at this time.
          Sincerly
          IMS Admin''' 
        send_mail(subject, 
            message, EMAIL_HOST_USER, [recepient], fail_silently = False)
   return render(request,'imsadmin/send_crejmail.html',{'comp':comp})

#supplier functions
def suppliers(request):
   supp=Suppliers.objects.all()
   context={
      'supp':supp
   }
   return render(request,'imsadmin/suppliers.html',context)
def sapprove(request,id):
   Suppliers.objects.filter(id=id).update(approve=True)
   supp=Suppliers.objects.all()
   context={
      'supp':supp
   }
   return render(request,'imsadmin/suppliers.html',context)
def sreject(request,id):
   Suppliers.objects.filter(id=id).update(reject=True)
   supp=Suppliers.objects.all()
   context={
      'supp':supp
   }
   return render(request,'imsadmin/suppliers.html',context)

def send_smail(request,id):
   supp=Suppliers.objects.get(id=id)
   #comp=Companies.objects.get(id=id)
   #sub = forms.Subscribe()
   if request.method == 'POST':
        sub = request.POST['email']
        name= request.POST['name']
        subject = 'Hi, '+format(name) 
        recepient = str(sub)
      
        # get random password pf length 8 with letters, digits, and symbols
        characters = string.ascii_letters + string.digits + string.punctuation
        password = ''.join(random.choice(characters) for i in range(8))
        Suppliers.objects.filter(id=id).update(sppwd=password)
        #Companies.objects.filter(id=id).update(cppwd=password)
        
        message = '''Welcome to OurWorkGem site.
        you can change automatically generated password after you login to your profile
        Steps you should follow for changing password:
        1) Login to your profile with autogenerated password
        2) After click on the profile button in the home page
        3) In that profile click on the change password button then you change the password
        You can login with this password : ''' +format(password)
        send_mail(subject, 
            message, EMAIL_HOST_USER, [recepient], fail_silently = False)
   return render(request,'imsadmin/send_smail.html',{'supp':supp})
def send_srejmail(request,id):
   supp=Suppliers.objects.get(id=id)
   #comp=Companies.objects.get(id=id)
   #sub = forms.Subscribe()
   if request.method == 'POST':
        sub = request.POST['email']
        name= request.POST['name']
        subject = 'Hi, '+format(name) 
        recepient = str(sub)
      
        # get random password pf length 8 with letters, digits, and symbols
        #characters = string.ascii_letters + string.digits + string.punctuation
        #password = ''.join(random.choice(characters) for i in range(8))
        #Suppliers.objects.filter(id=id).update(sppwd=password)
        #Companies.objects.filter(id=id).update(cppwd=password)
        
        message = '''Thank you for your interest in becoming a supplier.
          We appreciate your time and effort in completing the registration process.
          After careful consideration, we regret to inform you that we will not be able
          to proceed with your system at this time.
          Sincerly
          IMS Admin''' 
        send_mail(subject, 
            message, EMAIL_HOST_USER, [recepient], fail_silently = False)
   return render(request,'imsadmin/send_srejmail.html',{'supp':supp})

