# Generated by Django 4.2 on 2023-04-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companies_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companies',
            name='reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companies',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
