# Generated by Django 4.2 on 2023-05-04 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_suppliers_reject'),
        ('company', '0004_companies_approve_companies_reject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cprodname', models.CharField(max_length=20)),
                ('cproddesc', models.CharField(max_length=50)),
                ('cprodcatgry', models.CharField(max_length=20)),
                ('cprodbrand', models.BigIntegerField()),
                ('cprodimage', models.FileField(upload_to='product imgs')),
                ('cprodsppid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliers')),
            ],
        ),
    ]
