# Generated by Django 4.2 on 2023-05-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cprodsppid',
        ),
    ]
