# Generated by Django 4.2 on 2023-05-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_product_cprodsppid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cprodmaxqty',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cprodminqty',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cprodprice',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cprodstock',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cprodbrand',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
