# Generated by Django 4.2 on 2023-05-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_product_cprodmaxqty_product_cprodminqty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cprodbrand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
