# Generated by Django 4.2 on 2023-05-05 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cprodsppid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.productcategory'),
        ),
    ]
