# Generated by Django 4.2 on 2023-05-05 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_rename_cprodsppid_product_cprodcat_product_cmpid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cprodcatgry',
        ),
    ]
