# Generated by Django 4.2 on 2023-05-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_remove_product_cprodcatgry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='cmpid',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
