# Generated by Django 4.2 on 2023-05-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_remove_productcategory_cmpid_delete_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='cplogo',
            field=models.FileField(blank=True, null=True, upload_to='clogo'),
        ),
    ]
