# Generated by Django 4.2.1 on 2023-06-03 19:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0013_suppliers_splogo'),
        ('company', '0014_companies_cplogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasedate', models.DateField(default=datetime.date(2023, 6, 3))),
                ('purchaseno', models.BigIntegerField()),
                ('purchaseqty', models.BigIntegerField()),
                ('totalprice', models.BigIntegerField()),
                ('cmpid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companies')),
                ('prodid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.sproduct')),
                ('sprodcat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.sproductcategory')),
                ('supid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliers')),
            ],
        ),
    ]
