# Generated by Django 4.2.1 on 2023-06-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_cpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpurchase',
            name='sprodcat',
        ),
    ]
