# Generated by Django 4.2.1 on 2023-06-05 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_remove_cpurchase_sprodcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpurchase',
            name='orderstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cpurchase',
            name='paymentstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cpurchase',
            name='purchasedate',
            field=models.DateField(default=datetime.date(2023, 6, 5)),
        ),
    ]
