# Generated by Django 4.2 on 2023-04-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spname', models.CharField(max_length=20)),
                ('spmail', models.EmailField(max_length=254)),
                ('spphno', models.CharField(max_length=10)),
                ('spaddr', models.CharField(max_length=30)),
                ('spcity', models.CharField(max_length=20)),
                ('spstate', models.CharField(max_length=20)),
                ('spzip', models.CharField(max_length=20)),
                ('spcountry', models.CharField(max_length=20)),
                ('splic', models.CharField(max_length=20)),
                ('status', models.BooleanField(default='false')),
            ],
        ),
    ]
