# Generated by Django 4.2 on 2023-04-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_alter_suppliers_splic'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='sppwd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
