# Generated by Django 4.2 on 2023-04-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_suppliers_sppwd_alter_suppliers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='spphno',
            field=models.BigIntegerField(),
        ),
    ]
