# Generated by Django 4.2 on 2023-05-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_suppliers_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
