# Generated by Django 4.2 on 2023-05-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0010_sproductcategory_sproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sproduct',
            name='sprodimage',
            field=models.FileField(upload_to='sproduct imgs'),
        ),
    ]
